import Cart from './includes/Cart.js';
import MainScroll from './includes/MainScroll.js';
import Nav from './includes/Nav.js';
import Scrollup from './includes/Scrollup.js';
import Slider from './includes/Slider.js';
import WishCartSelect from './includes/WishCartSelect';
import Wish from './includes/Wish.js';
import ShopSortBy from './includes/ShopSortBy.js';
import Pagination from './includes/Pagaination';
import ShopCategory from './includes/ShopCategory';

Cart();
MainScroll();
Nav();
Scrollup();
WishCartSelect();
Wish();
ShopSortBy();
Pagination();
ShopCategory();